// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChehXekQ1XPvrQ9rFgFqxs52ADyyvsWik',
    appId: '1:665617780949:web:0ad25754c38935b605d25c',
    messagingSenderId: '665617780949',
    projectId: 'prm393-a3924',
    authDomain: 'prm393-a3924.firebaseapp.com',
    storageBucket: 'prm393-a3924.firebasestorage.app',
    measurementId: 'G-HHT2GN2EEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8hRcmu4S1pELKSRZEKcTkVELWXZYHRqw',
    appId: '1:665617780949:android:7ba3604e756faf6f05d25c',
    messagingSenderId: '665617780949',
    projectId: 'prm393-a3924',
    storageBucket: 'prm393-a3924.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChehXekQ1XPvrQ9rFgFqxs52ADyyvsWik',
    appId: '1:665617780949:web:c849b4fb4a4a99f005d25c',
    messagingSenderId: '665617780949',
    projectId: 'prm393-a3924',
    authDomain: 'prm393-a3924.firebaseapp.com',
    storageBucket: 'prm393-a3924.firebasestorage.app',
    measurementId: 'G-KHSNPK9PD7',
  );
}
